name: Build Kernel

permissions:
  contents: write
  actions: write

on:
  workflow_call:

jobs:
  build-begonia-a11-resukisu-susfs:
    name: "Redmi Note 8 Pro (Begonia) Android 11 ReSukiSU+SuSFS"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-begonia-full.yml
    secrets: inherit

  build-begonia-a11-resukisu:
    name: "Redmi Note 8 Pro (Begonia) Android 11 ReSukiSU"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-begonia.yml
    secrets: inherit

